{
	"version": 1571194396,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/button_legkoslova-sheet0.png",
		"images/button_slozhnopredlozheniya-sheet0.png",
		"images/button_sredneslovosochetaniya-sheet0.png",
		"images/button_trenirovkabukvy-sheet0.png",
		"images/893f1afef2ef5934e1186111db6d-sheet0.png",
		"images/pasep015sh-sheet0.png",
		"images/spritefont.png",
		"images/sprite-sheet0.png",
		"images/button_ok-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"media/Сказочный Патруль - Сказочный Патруль - Саундтрек №2 (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"Вопросы.txt",
		"jquery.gritter.js",
		"jquery.gritter.css"
	]
}